name: Sync File

on:
  schedule:
    - cron: '0 0 * * *' # 每天定时运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: SuperManito/LinuxMirrors # 替换为源仓库的所有者和仓库名
        path: source_repo
        ref: main # 替换为源仓库的分支名

    - name: Copy file from source repository
      run: |
        cp source_repo/path/to/your/file ./path/to/your/destination

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Sync file from source repository" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
