name: Sync LinuxMirrors

on:
  schedule:
    # 每天凌晨1点运行同步任务
    - cron: '0 1 * * *'
  workflow_dispatch:
    # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: SuperManito/LinuxMirrors
        path: src

    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        path: target
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync repository
      run: |
        rsync -a --delete src/ target/
        cd target
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Sync from SuperManito/LinuxMirrors" || echo "No changes to commit"
        git push origin main
